# nixpacks.toml

[project]
name = "hls-telegram-bot"

[phases.setup]
nixPkgs = ["python3", "ffmpeg"]

[phases.install]
cmds = [
  # activate the venv that Nixpacks created at /opt/venv
  "source /opt/venv/bin/activate",
  "pip install -r requirements.txt"
]

[start]
cmd = "python bot.py"
