# nixpacks.toml
[project]
name = "hls-telegram-bot"

[phases.setup]
nixPkgs = ["ffmpeg"]      # install ffmpeg so your bot's ffmpeg calls work

[start]
cmd = "python bot.py"     # what gets run when the container starts
