# nixpacks.toml
[project]
name = "hls-telegram-bot"  # optional friendly name

[phases.setup]
# <-- MUST be "packages", not nixPkgs or nixpkgs
packages = ["python3", "ffmpeg"]

# we do NOT override install. Nixpacks will see your requirements.txt
# and automatically do: pip install -r requirements.txt

[start]
# The single command to launch your bot once the container is built
cmd = "python bot.py"
