# nixpacks.toml

[project]
name = "hls-telegram-bot"  # optional

# 1) install any OS‐level packages you need
[phases.setup]
nixPkgs = ["python3", "ffmpeg"]

# 2) install your Python deps (into the venv Nixpacks auto-creates)
[phases.install]
cmds = ["pip install -r requirements.txt"]

# 3) override the container start command
[start]
cmd = "python bot.py"
